name: Preparar y Desplegar Web

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Inyectar Analytics y Footer Automático
        run: |
          # 1. Inyectar código de Google Analytics
          GA_CODE='<script async src="https://www.googletagmanager.com/gtag/js?id=G-B14TF44M7Z"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag("js",new Date());gtag("config","G-B14TF44M7Z");</script>'
          find . -name "*.html" -type f -exec sed -i "s@</head>@$GA_CODE</head>@gI" {} +

          # 2. Reemplazar Footer en todos los archivos
          FOOTER_CODE='<footer style="text-align: center; font-size: 10px; opacity: 0.7; margin-top: 40px;"><p style="font-size: 10px; margin-bottom: 10px; max-width: 800px; margin-left: auto; margin-right: auto; line-height: 1.2;"><strong>Aviso legal:</strong> Neurotools es una herramienta de apoyo diseñada exclusivamente para profesionales sanitarios. Proyecto desarrollado por especialistas en Neurología. Los resultados obtenidos mediante estas calculadoras y algoritmos no sustituyen el juicio clínico, el diagnóstico individualizado ni las guías de práctica clínica oficiales.</p>NEUROTOOLS · v. 2026.05 · neurotoolsrecursos\@gmail.com (MIT License)<br><a href="/code-of-conduct.html" style="color: inherit; text-decoration: underline;">Code of Conduct</a></footer>'
          find . -name "*.html" -type f -exec perl -0777 -pi -e "s|<footer>.*?</footer>|$FOOTER_CODE|gs" {} +

      - name: Generar archivo Sitemap.xml
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://neurotools.es/

      - name: Configurar entorno de GitHub Pages
        uses: actions/configure-pages@v4

      - name: Empaquetar los archivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Desplegar en la web
        id: deployment
        uses: actions/deploy-pages@v4
